### PR TITLE
Fix scaling decoding and munin race condition

### LINKED ISSUE #18: mismatch errors
Hello, I  downloaded the latest version of the branch on my raspberry pi 3 and it works,  but we have not managed to make it work the right way. 
I get the wrong values

multigraph in_batvolt
volt.value 0.00
multigraph in_batcharge
charge.value 0.00
multigraph in_batcurrent
current.value 0.00
multigraph in_batpower
power.value 0.00
multigraph in_mainscurrent
currentin.value 128.59
currentout.value -12.48
multigraph in_mainsvoltage
voltagein.value 207.35
voltageout.value 207.35
multigraph in_mainspower
powerin.value 26662.97
powerout.value -2586.85
multigraph in_mainsfreq
freqin.value 0.36
freqout.value 1.10

Is there any way to ask the investor only the securities I need?

For example, I want to consult only currents and the actual power, I see that with winmon commands you can query variables. 
I was thinking of using py.serial  by querying the current snapshot in the format indicated in the document (04 FF 'A' 01 00 BB), I have been reading but I still do not know if I am doing the right thing. 
I assume the format is fine, but I don't want to fail my inverter when testing. 
I don't quite understand how to make my new consultation to bring these values that I tell you.
Saludos my friend and thanks for your contribution

### LINKED ISSUE #19: Race condition in munin output.
The munin output code sends a pointer to a struct over a channel and the immediately writes to that struct at https://github.com/diebietse/invertergui/blob/55ae241d9236eca23012c3c596b9ca85efbb153b/plugins/munin/munin.go#L125

This causes a race condition and can cause corruption in the munin output. https://github.com/diebietse/invertergui/tree/scalefixes should fix this issue.

### PR DESCRIPTION
**Pull request by hpdvanwyk**
Fixes for https://github.com/diebietse/invertergui/issues/19 and https://github.com/diebietse/invertergui/issues/18

### CODE REVIEW

File: mk2driver/mk2.go [hunk 1]
```diff
@@ -236,9 +236,21 @@ func (m *mk2Ser) reqScaleFactor(in byte) {
 // Decode the scale factor frame.
 func (m *mk2Ser) scaleDecode(frame []byte) {
 	tmp := scaling{}
+	logrus.Infof("Scale frame(%d): 0x%x", len(frame), frame)
```
Comment (ncthompson) [inline mk2driver/mk2.go]: This could be left out now with the later changes

**Review by ncthompson — APPROVED** [review]
